version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Alturos.PanTilt.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: 8J1h8X7v1xCpJXCBK+lpEiqUW88V2B5we5m5uDXFFyu/kEgSAJeRZnj1sv/Vq7a2