version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Alturos.PanTilt.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: BMILy6I+lYAdm6g/OGOGsqsg+mYjzwbfQDGV7ZicNLcMdg9uMjGcbKlQ97ZCYLO3
  artifact: /.*\.nupkg/
